CREATE TABLE IF NOT EXISTS User(
	id TEXT PRIMARY KEY,
	passwd TEXT NOT NULL,
	alias TEXT NOT NULL,
	authority INTEGER NOT NULL,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
