CREATE TABLE User(
	id TEXT PRIMARY KEY AUTOINCREMENT,
	password_sha TEXT NOT NULL,
	alias TEXT NOT NULL,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
