[package]
name = "config-it"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "*"
serde = "*"
serde_json = "*"
erased-serde = "*"
smartstring = { version = "*", features = ["serde"] }
thiserror = "*"
async-channel = "*"
oneshot = "*"
log = "*"
async-mutex = "*"
smallvec = { version = "*", features = ["serde", "write", "union"] }
