[package]
name = "config-it"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1"
serde = "1"
serde_json = "1"
erased-serde = "0.3"
smartstring = { version = "1", features = ["serde"] }
thiserror = "1"
async-channel = "1"
async-broadcast = "0.4"
oneshot = "0.1"
log = "0.4"
smallvec = { version = "1", features = ["serde", "write", "union"] }
lazy_static = "1"
futures = "0.3"
arc-swap = "1"
macros = { package = "config-it-macros", path = "../config-it-macros", version = "*" }
