[package]
name = "config-it"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.15.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
erased-serde = "0.3"
itertools = "0.10"
fnv = "1"
tokio = { version = "1", optional = true, features = ["sync"] }
smol_str = { version = "0.1", features = ["serde"] }

[features]
tokio = ["dep:tokio"]


