[package]
name = "config-it"
version = "0.1.2"
edition = "2021"
description = "Centralized dynamic configuration management"
authors = ["kang-sw <ki6080@gmail.com>"]
categories = ["config"]
repository = "https://github.com/kang-sw/config-it-rs"
keywords = ["config"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macros = { package = "config-it-macros", path = "../config-it-macros", version = "0.1.2" }

serde = { version = "1", features = ["derive"] }
serde_json = "1"
erased-serde = "0.3"

once_cell = "1"
thiserror = "1"

smartstring = { version = "1", features = ["serde"] }
flume = "0"
async-broadcast = "0.5"
futures = "0.3"

oneshot = "0.1"
log = "0.4"

smallvec = { version = "1", features = ["serde", "write", "union"] }
arc-swap = "1"

lazy_static = "1"
parking_lot = "0"
