[package]
name = "config-it"
version = "0.0.1"
edition = "2021"
description = "Dynamic application config management"
authors = ["kang-sw <ki6080@gmail.com>"]
categories = ["config"]
repository = "https://github.com/kang-sw/config-it-rs"
keywords = ["config"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
erased-serde = "0.3"
smartstring = { version = "1", features = ["serde"] }
thiserror = "1"
async-channel = "1"
async-broadcast = "0.4"
oneshot = "0.1"
log = "0.4"
smallvec = { version = "1", features = ["serde", "write", "union"] }
lazy_static = "1"
futures = "0.3"
arc-swap = "1"
macros = { package = "config-it-macros", path = "../config-it-macros", version = "*", optional = true }

[features]
derive = ["dep:macros"]
