[package]
name = "config-it"
version = "0.8.0"
edition = "2021"
description = "Centralized dynamic configuration management"
authors = ["kang-sw <ki6080@gmail.com>"]
categories = ["config"]
repository = "https://github.com/kang-sw/config-it-rs"
keywords = ["config"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# ------------------------------------------------------------------------------------------------ #
#                                               CORE                                               #
# ------------------------------------------------------------------------------------------------ #

serde = { version = "1", features = ["derive"] }
serde_json = "1"
erased-serde = "0.3"

strseq = { version = "0.1", features = ["serde"] }
compact_str = { version = "0.7", features = ["serde"] }
indexmap = { version = "2.0.0", features = ["serde"], optional = true }

bitflags = { version = "2.4.0", features = ["serde"] }

derive_more = "0.99"

# ------------------------------------------------------------------------------------------------ #
#                                              CONFIG                                              #
# ------------------------------------------------------------------------------------------------ #

thiserror = { version = "1", optional = true }

smallvec = { version = "1", features = ["serde"], optional = true }
log = { version = "0.4", optional = true }
dashmap = { version = "5.5.3", optional = true }

derive_setters = { version = "0.1.6", optional = true }

memoffset = { version = "0.9.0", optional = true }
parking_lot = { version = "0.12.0", optional = true }
bitfield = { version = "0.14.0", optional = true }

machine-uid = { version = "0.5.1", optional = true }
aes-gcm = { version = "0.10.3", optional = true }
cs = { version = "0.5.1", package = "custom_debug_derive", optional = true }
impls = { version = "1.0.3", optional = true }

[dependencies.macros]
package = "config-it-macros"
path = "../core-macros"
version = "0.5.0"
optional = true

[dependencies.schemars]
version = "0.8.12"
features = ["preserve_order"]
optional = true

[dev-dependencies]
futures = "0.3"
serde_yaml = "0"
indoc = "2"
tokio = { version = "1", features = ["full"] }

[features]
default = ["config", "indexmap", "jsonschema"]

config = [
	"config-derive",
	"dep:thiserror",
	"dep:log",
	"dep:dashmap",
	"dep:derive_setters",
	"dep:parking_lot",
	"dep:smallvec",
	"dep:bitfield",
	"dep:cs",
]

machine-id-encryption = ["dep:machine-uid", "encryption"]
config-derive = ["dep:memoffset", "dep:impls"]
encryption = ["dep:aes-gcm"]

indexmap = ["dep:indexmap"]
jsonschema = ["dep:schemars", "macros/jsonschema"]
