// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface LoginReply { expire_utc_ms: bigint, user_alias: string, authority: number, user_id: string, }