[package]
name = "config-it-macros"
version = "0.5.4"
edition = "2021"
authors = ["kang-sw <ki6080@gmail.com>"]
categories = ["config"]
repository = "https://github.com/kang-sw/config-it-rs"
license = "MIT"
description = "Implements derive macro for config-it"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
proc-macro-crate = "2"
proc-macro-error = "1.0.4"

[features]
jsonschema = []
